input_max_length: 8192,16384,32768,65536,131072
datasets: triviaqa,triviaqa,triviaqa,triviaqa,triviaqa
generation_max_length: 128,128,128,128,128
test_files: vrag/viquae_K8_dep6.jsonl,vrag/viquae_K16_dep6.jsonl,vrag/viquae_K32_dep6.jsonl,vrag/viquae_K64_dep6.jsonl,vrag/viquae_K128_dep6.jsonl
use_chat_template: true
max_test_samples: 100
