input_max_length: 8192,16384,32768,65536,131072
datasets: text_doc,text_doc,text_doc,text_doc,text_doc
generation_max_length: 128,128,128,128,128
test_files: documentQA/text_mmlongdoc_K8.jsonl,documentQA/text_mmlongdoc_K16.jsonl,documentQA/text_mmlongdoc_K32.jsonl,documentQA/text_mmlongdoc_K64.jsonl,documentQA/text_mmlongdoc_K128.jsonl
use_chat_template: true
max_test_samples: 100
