input_max_length: 8192,16384,32768,65536,131072,8192,16384,32768,65536,131072
datasets: vh_single,vh_single,vh_single,vh_single,vh_single,vh_multi,vh_multi,vh_multi,vh_multi,vh_multi
generation_max_length: 128,128,128,128,128,128,128,128,128,128
test_files: NIAH/vh_single_test_1000_K8_dep6.jsonl,NIAH/vh_single_test_1000_K16_dep6.jsonl,NIAH/vh_single_test_1000_K32_dep6.jsonl,NIAH/vh_single_test_1000_K64_dep6.jsonl,NIAH/vh_single_test_1000_K128_dep6.jsonl,NIAH/vh_multi_test_1000_K8_dep3.jsonl,NIAH/vh_multi_test_1000_K16_dep3.jsonl,NIAH/vh_multi_test_1000_K32_dep3.jsonl,NIAH/vh_multi_test_1000_K64_dep3.jsonl,NIAH/vh_multi_test_1000_K128_dep3.jsonl
use_chat_template: true
max_test_samples: 100
